# Generated by Django 4.2.6 on 2024-04-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_project", models.CharField(max_length=200)),
                ("description_project", models.TextField(max_length=3000)),
                ("image_project", models.ImageField(upload_to="img_db/")),
                ("genere_project", models.CharField(max_length=15)),
                ("link_project", models.URLField()),
            ],
        ),
    ]
