# Generated by Django 4.2.6 on 2024-04-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CVMain", "0002_alter_project_image_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="sum_description_project",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="title_project",
            field=models.CharField(max_length=30),
        ),
    ]
