# Generated by Django 4.2.6 on 2024-04-21 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CVMain", "0003_project_sum_description_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="team_member",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_project",
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name="project",
            name="sum_description_project",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("comment", models.TextField(max_length=300)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="CVMain.project",
                    ),
                ),
            ],
        ),
    ]
