# Generated by Django 4.2.6 on 2024-04-22 07:57

import CVMain.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CVMain", "0004_project_team_member_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="description_project",
        ),
        migrations.AddField(
            model_name="project",
            name="description_project_1",
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="description_project_2",
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="description_project_3",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="description_project_4",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="img_1",
            field=models.ImageField(
                blank=True, null=True, upload_to=CVMain.models.upload_to
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="img_2",
            field=models.ImageField(
                blank=True, null=True, upload_to=CVMain.models.upload_to
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="img_3",
            field=models.ImageField(
                blank=True, null=True, upload_to=CVMain.models.upload_to
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="img_4",
            field=models.ImageField(
                blank=True, null=True, upload_to=CVMain.models.upload_to
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image_project",
            field=models.ImageField(upload_to=CVMain.models.upload_to),
        ),
    ]
