# Generated by Django 4.2.6 on 2024-04-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CVMain", "0005_remove_project_description_project_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField(max_length=3000)),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
