# Generated by Django 4.2.6 on 2024-04-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CVMain", "0006_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="end",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="start",
            field=models.DateField(null=True),
        ),
    ]
