# Generated by Django 4.2.6 on 2024-05-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVMain', '0008_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='back',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='front',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='laungue',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
