# Generated by Django 4.2.6 on 2024-05-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVMain', '0009_project_back_project_front_project_laungue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='back',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='front',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='laungue',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
